// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "848039f7-e10f-4c4e-bc37-4ad276088486";

const char SSID[]               = "Apple";    // Network SSID (name)
const char PASS[]               = "123456789";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "2XTRveHl8dEJFzT4rO3LKl1ub";    // Secret device password

void onLedChange();

bool led;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(led, READWRITE, ON_CHANGE, onLedChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
